# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "terragrunt/terraform.tfstate"
    resource_group_name  = "rg-stg_1"
    storage_account_name = "terracloudtfstate"
  }
}
